### ISSUE TITLE
Improvements checklist

### ISSUE THREAD

**Issue by smf8** [smf8/gokkan#1]
- [ ] Write unit tests for all packages.
- [ ] Add Prometheus monitoring for endpoints and repositories.
- [ ] Add cloud deployment options (helm or deployment).
- [ ] Improve JWT token management (token blocking).
